services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.7.1
    platform: linux/amd64
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      sdp_net:
        ipv4_address: 172.20.0.10
    ports:
      - 2181:2181
    volumes: 
      - zookeeper_data:/var/lib/zookeeper/data
      - zookeeper_datalog:/var/lib/zookeeper/log

  kafka:
    image: confluentinc/cp-kafka:7.7.1
    platform: linux/amd64
    container_name: kafka-broker
    depends_on:
      - zookeeper
    networks:
      sdp_net:
        ipv4_address: 172.20.0.11
    ports:
      - 29092:29092
    restart: always
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka_data:/var/lib/kafka/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "action.auto_create_index=true"
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - es_data:/usr/share/elasticsearch/data
    networks:
      sdp_net:
        ipv4_address: 172.20.0.12
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  kibana:
    image: docker.elastic.co/kibana/kibana:8.16.1
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    networks:
      sdp_net:
        ipv4_address: 172.20.0.13
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  kafka-connect:
    image: confluentinc/cp-kafka-connect:6.2.10.amd64
    container_name: kafka-connect
    env_file:
      - .env 
    networks:
      sdp_net:
        ipv4_address: 172.20.0.14
    ports:
      - "28083:28083"
    depends_on:
      - kafka
      - elasticsearch
    volumes: 
      - kafka_connect_data:/var/lib/kafka/data
      - kafka_connect_es_plugin:/usr/share/confluent-hub-components

volumes:
  es_data:
    driver: local
  zookeeper_data: 
    driver: local
  zookeeper_datalog: 
    driver: local

  kafka_data: 
    driver: local

  kafka_connect_data: 
    driver: local
  # kafka_connect_plugins: 
  #   driver: local
  kafka_connect_es_plugin:
    driver: local

# Network for streaming data pipeline
networks:
  sdp_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
